version: '3.7'
services:
  centos01-filebeat:
    hostname: centos01-filebeat
    image: docker.elastic.co/beats/filebeat:${ELASTIC_KIBANA_VERSION}
    user: root
    networks:
      - elk
    volumes:
      - type: bind
        source: ./filebeat/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
        read_only: true
      - filebeat_data:/usr/share/filebeat/data
      - /var/run/docker.sock:/var/run/docker.sock
      # This is needed for filebeat to load container log path as specified in filebeat.yml
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      # This is needed for filebeat to load logs for system and auth modules
      - /var/log/:/var/log/:ro
      # This is needed for filebeat to load logs for auditd module
      # - /var/log/audit/:/var/log/audit/:ro
    environment:
      - ELASTICSEARCH_HOST=${ELASTIC_KIBANA_HOST}
      - KIBANA_HOST=${ELASTIC_KIBANA_HOST}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_KIBANA_PASSWORD}
    # disable strict permission checks
    command: ["--strict.perms=false"]

  centos01-metricbeat:
    image: docker.elastic.co/beats/metricbeat:${ELASTIC_KIBANA_VERSION}
    # https://github.com/docker/swarmkit/issues/1951
    hostname: centos01-metricbeat
    user: root
    networks:
      - elk
    volumes:
      - type: bind
        source: ./metricbeat/metricbeat.yml
        target: /usr/share/metricbeat/metricbeat.yml
        read_only: true
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - metricbeat_data:/usr/share/metricbeat/data
    environment:
      - ELASTICSEARCH_HOST=${ELASTIC_KIBANA_HOST}
      - KIBANA_HOST=${ELASTIC_KIBANA_HOST}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_KIBANA_PASSWORD}
    # disable strict permission checks
    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]

volumes:
  filebeat_data:
    driver: local
  metricbeat_data:
    driver: local

networks:
  elk:
    driver: bridge

